### PR TITLE
WIP: Mfaverified only zone

### PR DESCRIPTION
**Pull request by mrvahedi68**

### CODE REVIEW

**Comment by michielbdejong** [comment]
What is this PR/branch for? The branch title is almost identical to the project title so it can describe almost anything. :)

**Comment by mrvahedi68** [comment]
We have no changes in this project and only may add new submodules to that.

**Comment by mrvahedi68** [comment]
It's not related to [Milestone 5 ](https://github.com/pondersource/nextcloud-mfa-awareness/milestone/5)  and I use it for testing only. We can merge it and then I will use main branch for test.

**Review by michielbdejong — APPROVED** [review]

**Comment by michielbdejong** [comment]
Great! I clicked "approve", you can go ahead and merge it now.

**Comment by michielbdejong** [comment]
Thanks for explaining, I now understand what this PR is and why it didn't have a clear name.

Agreed, if this branch is what you are using and nobody is using the main branch anymore, then this should become the main branch.

**Comment by mrvahedi68** [comment]
Yes, agree with you. I think if we need to add some submodules for running inside the nextcloud and testing we can create another branch. The name of this branch is not suitable for this approach.

**Pull request merged**
